export type Audience = "research" | "engineering" | "analytics";
export type Maturity = "Research Prototype" | "Full-Stack Prototype" | "Core Harness Implemented" | "Production Deployment" | "Course-Supervised Research" | "Hackathon Prototype" | "Under Development" | "Historical Project";
export interface Evidence { label: string; value: string; note?: string }
export interface Project {
  name: string; title: string; slug: string; dates: string; description: string; caseStudy: string;
  type: string; maturity: Maturity; audiences: Audience[]; researchQuestion?: string; problem: string;
  contribution: string[]; architecture: string[]; methods: string[]; stack: string[]; evidence: Evidence[];
  limitations: string[]; nextSteps: string[]; images: { src: string; alt: string }[];
  links: { label: string; href: string }[]; featured: boolean; public: boolean;
}

const project = (value: Project) => value;
export const projects: Project[] = [
  project({name:"NetMap",title:"Consent-Aware Temporal Trust Infrastructure",slug:"netmap",dates:"Current",description:"Trust-graph and recommendation infrastructure that treats consent and time as system constraints.",caseStudy:"NetMap explores how recommendations can respect changing relationships, introduction consent, and bounded contact.",type:"Human-centered AI systems",maturity:"Research Prototype",audiences:["research","engineering"],researchQuestion:"Can temporally weighted, consent-aware trust graphs support safer, more relevant recommendations than static graphs?",problem:"Static relationship graphs flatten time and can route introductions without representing each person’s authority.",contribution:["Designed the trust, consent, and routing model","Implemented prototype API and graph infrastructure"],architecture:["Temporal trust weighting","Dijkstra-based routing over composite friction","willIntroduce consent gates","Multi-party approval state and contact quotas"],methods:["Graph modeling","ReAct-style tool loops","API design"],stack:["Python","FastAPI","PostgreSQL","pgvector","Graph algorithms"],evidence:[],limitations:["Evaluation has not yet been conducted","No completed real-world study or publication is claimed"],nextSteps:["Define comparison protocol against static-graph baselines","Evaluate recommendation relevance and consent outcomes"],images:[],links:[],featured:true,public:true}),
  project({name:"HPC OS",title:"Evidence-Centered School Management & Assessment",slug:"hpc-os",dates:"Current",description:"AI-assisted assessment where drafts cannot reach students before educator review.",caseStudy:"HPC OS makes educator authority an enforced workflow state rather than an interface suggestion.",type:"Educational AI system",maturity:"Full-Stack Prototype",audiences:["research","engineering"],researchQuestion:"How does enforced educator review affect correction behavior, automation bias, and trust in AI-assisted assessment?",problem:"Generated assessment feedback can appear authoritative before a qualified educator has checked it.",contribution:["Built the full-stack prototype architecture","Implemented review-gated publication states"],architecture:["Fastify service boundary","Draft → educator review → release state machine","PostgreSQL/Supabase data layer","Railway and Vercel deployment history"],methods:["Human-in-the-loop workflow design","State modeling"],stack:["TypeScript","Fastify","Node.js","React","PostgreSQL","Supabase","Railway","Vercel"],evidence:[{label:"Implemented",value:"Review-gated architecture"}],limitations:["Educator study has not yet been conducted"],nextSteps:["Design and run an educator study","Measure corrections and trust calibration"],images:[],links:[],featured:true,public:true}),
  project({name:"Multi-Provider AI Workflow & Automation Engine",title:"Resilient Orchestration with Human Escalation",slug:"automation-engine",dates:"Current",description:"Provider-aware orchestration with structured outputs, instrumentation, and explicit human approval.",caseStudy:"The core harness makes failure, cost, and consequence visible inputs to orchestration decisions.",type:"Agent infrastructure",maturity:"Core Harness Implemented",audiences:["research","engineering"],researchQuestion:"Under what failure, cost, and consequence conditions should an agent continue, retry, switch providers, pause, or escalate?",problem:"Single-provider AI workflows often obscure failure modes and lack a controlled path to human judgment.",contribution:["Implemented the core multi-provider harness","Added observable request and approval boundaries"],architecture:["Four-provider routing and fallback","Schema-constrained outputs","Per-request cost, token, and latency instrumentation","Human approval gates","Tenant-scoped credential handling"],methods:["Failure-aware orchestration","Structured-output validation"],stack:["Python","TypeScript","Claude","Gemini","Groq","OpenRouter","Supabase","Scheduled workflows"],evidence:[{label:"Implemented",value:"Core orchestration harness"}],limitations:["Larger production integration remains incomplete","No self-correction claim is made"],nextSteps:["Complete broader integration","Evaluate escalation policy tradeoffs"],images:[],links:[],featured:true,public:true}),
  project({name:"Zwitter",title:"Human-Centered Service-Operations Intelligence",slug:"zwitter",dates:"Current",description:"Service-operations software designed to recommend rather than assign work.",caseStudy:"Zwitter separates a client-deployed operational subsystem from broader exploratory assistance modules.",type:"Operations system",maturity:"Production Deployment",audiences:["research","engineering","analytics"],researchQuestion:"How can AI assist service operations without employment-like control?",problem:"Operational assistance can quietly become opaque task assignment or worker control.",contribution:["Designed recommendation-not-assignment boundaries","Delivered an operational subsystem for Chaitrali’s Kitchen"],architecture:["Recommendation boundary","Operational subsystem","Broader partial modules"],methods:["Human-centered workflow design","Operations analysis"],stack:["TypeScript","PostgreSQL"],evidence:[{label:"Deployed",value:"Operational subsystem",note:"Broader modules remain partial."}],limitations:["Only the operational subsystem is described as deployed","No customer-level data is published"],nextSteps:["Complete and separately validate broader modules"],images:[],links:[],featured:true,public:true}),
  project({name:"AKTIVIQ",title:"AI-Assisted Professional Education & Certification",slug:"aktiviq",dates:"Current",description:"A generator/evaluator education platform with explicit certification checkpoints.",caseStudy:"Generation and evaluation are separate system responsibilities; progression includes administrator approval.",type:"Educational platform",maturity:"Under Development",audiences:["research","engineering"],problem:"A single generative pass should not validate its own educational output or certification progress.",contribution:["Designed separated generation/evaluation flows","Built platform infrastructure and approval checkpoints"],architecture:["Separate generator and evaluator","Certification checkpoints","Administrator approval"],methods:["Workflow state modeling","Content infrastructure"],stack:["Next.js","React","TypeScript","Supabase","PostgreSQL","Stripe","MDX","Claude API"],evidence:[],limitations:["Infrastructure is ahead of curriculum"],nextSteps:["Develop and audit curriculum","Validate evaluation flows"],images:[],links:[],featured:false,public:true}),
  project({name:"StatusGuard",title:"Verifiable Document & Evidence Platform",slug:"statusguard",dates:"Current",description:"Document organization that separates AI assistance from external or legal authority.",caseStudy:"StatusGuard uses mandatory review and evidence manifests while keeping designed provenance features distinct from demonstrated ones.",type:"Evidence system",maturity:"Full-Stack Prototype",audiences:["research","engineering"],problem:"OCR and AI assistance can be mistaken for authoritative verification or legal judgment.",contribution:["Designed review boundaries and evidence manifests"],architecture:["OCR with mandatory user review","SHA-256 evidence manifests","Designed provenance and timestamping architecture"],methods:["Evidence integrity","Human review"],stack:["OCR","SHA-256","TypeScript"],evidence:[],limitations:["RFC 3161 end-to-end operation is not claimed","The system does not provide legal advice, eligibility decisions, government verification, or adjudication"],nextSteps:["Verify timestamping end to end before describing it as implemented"],images:[],links:[],featured:false,public:true}),
  project({name:"BUDA II",title:"Institutional RAG Assistant",slug:"buda-ii",dates:"March 2025",description:"A local retrieval workflow for grounded institutional information answers.",caseStudy:"Built independently for an IEEE Hackathon using a crawled Clark University corpus and local inference.",type:"Hackathon project",maturity:"Hackathon Prototype",audiences:["engineering","analytics"],problem:"Institutional information is distributed across many web pages and difficult to retrieve consistently.",contribution:["Solo project: scraping, retrieval pipeline, and local answer generation"],architecture:["Web corpus ingestion","Local embeddings and retrieval","Ollama response generation"],methods:["RAG","Local inference"],stack:["Python","Ollama","Local embeddings"],evidence:[{label:"Corpus",value:"2,000+ pages",note:"Clark University web pages scraped for the prototype."}],limitations:["Hackathon prototype; no production deployment is claimed"],nextSteps:["Evaluate retrieval and answer grounding systematically"],images:[],links:[],featured:false,public:true}),
  project({name:"Vibraille",title:"Real-Time 2D-to-3D Floor Analysis & Proximity-Aware Navigation",slug:"vibraille",dates:"March 2025",description:"A floor-analysis and navigation concept for visually impaired users.",caseStudy:"An individual C4 Hackathon project converting floor-plan signals into navigable spatial representations.",type:"Computer vision",maturity:"Hackathon Prototype",audiences:["research","engineering"],problem:"Two-dimensional floor plans do not directly provide accessible, proximity-aware navigation cues.",contribution:["Individual project spanning detection, depth, segmentation, and navigation logic"],architecture:["Object detection","Depth estimation","Room segmentation","Navigation logic"],methods:["Computer vision","Spatial reasoning"],stack:["YOLOv8","MiDaS","Python"],evidence:[],limitations:["No quarantined training-accuracy figure is published","No deployment is claimed"],nextSteps:["Evaluate navigation quality with appropriate users and safety protocols"],images:[],links:[],featured:false,public:true}),
  project({name:"Scalable Healthcare Risk Modeling",title:"Stroke Prediction with Imbalanced Data",slug:"stroke-prediction",dates:"Clark University · BAN 5600",description:"A supervised PySpark modeling project focused on an honest sensitivity/discrimination tradeoff.",caseStudy:"Completed under Dr. Jin Fang, the project uses modest recall as a decision-support limitation rather than hiding it.",type:"Course-supervised ML",maturity:"Course-Supervised Research",audiences:["research","analytics","engineering"],problem:"Rare health outcomes create class-imbalance challenges where headline discrimination can obscure missed positives.",contribution:["Built the PySpark pipeline and Gradient Boosted Trees model"],architecture:["Distributed preprocessing","Gradient Boosted Trees evaluation"],methods:["Imbalanced classification","Model evaluation"],stack:["PySpark","Spark","Gradient Boosted Trees"],evidence:[{label:"ROC-AUC",value:"0.85"},{label:"Recall",value:"0.32",note:"Reported openly as a decision-support limitation."}],limitations:["Recall of 0.32 limits sensitivity and suitability for consequential use"],nextSteps:["Study threshold and imbalance interventions"],images:[],links:[],featured:false,public:true}),
  project({name:"IIT Kanpur ISMRITI Hybrid Recommender",title:"Hybrid Movie Recommendation Research",slug:"ismriti-recommender",dates:"2019",description:"A supervised hybrid recommender combining collaborative and content retrieval.",caseStudy:"Research internship supervised by Prof. Laxmidhar Behera; led a project team and built a Flask interface over MovieLens experiments.",type:"Supervised research",maturity:"Historical Project",audiences:["research","analytics","engineering"],problem:"Single recommendation strategies capture only part of preference and item similarity.",contribution:["Led the project team","Integrated recommendation methods and interface"],architecture:["Neural collaborative filtering","Pearson-neighborhood method","TF-IDF/cosine content retrieval","Flask interface"],methods:["Recommender systems","Held-out evaluation"],stack:["Python","TensorFlow","Flask","TF-IDF"],evidence:[{label:"Held-out MAE",value:"≈0.68",note:"MovieLens ratings on a five-star scale; not classification accuracy."}],limitations:["Historical academic system; no production claim"],nextSteps:["Revisit with contemporary evaluation and user-centered measures"],images:[],links:[],featured:false,public:true})
];

export const profile = {
  name:"Soumyabrata Ghosh", location:"Fort Collins, Colorado", email:"soumyabrata.ghosh@colostate.edu",
  positioning:"Human-Centered AI · Trustworthy AI · Human–Agent Decision Systems",
  statement:"I build AI systems where human authority, evidence, consent, and failure handling are part of the architecture.",
  introduction:"M.S. Computer Science student at Colorado State University with an M.S. in Business Analytics from Clark University, research training at IIT Kanpur, and experience building AI, data, and software systems.",
  canonicalUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://example.com", resumeUrl: null as string | null,
  social: { github: null as string | null, linkedin: null as string | null }
};
export const education = [
  {degree:"M.S. Computer Science",school:"Colorado State University",dates:"2026–Present"},
  {degree:"M.S. Business Analytics",school:"Clark University",dates:"2023–2025",detail:"GPA 3.61/4.00"},
  {degree:"PGDM Business Analytics",school:"IISWBM",dates:"2018–2019"},
  {degree:"B.Sc. (Hons.) Chemistry",school:"Chakdaha College, University of Kalyani",dates:"2015–2019"}
];
export const experiences = [
  {title:"Research training",org:"IIT Kanpur",dates:"2019",text:"Led a supervised team developing a hybrid recommender during the ISMRITI program."},
  {title:"Business Operations Manager & Analyst",org:"Bharti AXA Life Insurance",dates:"Oct 2021–Aug 2022",text:"Redesigned workflows through Excel automation, tracking, call scheduling, and escalation rules. Company-assessed productivity improved 31%; ranked 19th nationally in renewal collections in FY2021–22; contributed approximately $52K in combined renewal, retention, and new revenue over five months; received a 25% salary raise."},
  {title:"Financial advisory and sales",org:"HDFC ERGO",dates:"Earlier career",text:"Built experience connecting customer needs, financial products, and operational outcomes."},
  {title:"Founder & Lead Chemistry Instructor",org:"Mutual Learning",dates:"5+ years",text:"Mentored 200+ learners; 25+ progressed into IITs, NITs, and AIIMS."}
];
export const lenses: Record<Audience,{eyebrow:string;title:string;description:string;focus:string[]}> = {
 research:{eyebrow:"Research lens",title:"Human authority as a system property",description:"Research questions and prototypes across trustworthy AI, consent, evidence, and human–agent decisions.",focus:["Research questions","Supervised work","Evaluation boundaries"]},
 engineering:{eyebrow:"Engineering lens",title:"Reliable systems around uncertain models",description:"Architecture, backend and data infrastructure, provider failure handling, and human approval mechanisms.",focus:["Architecture","Reliability","Implementation"]},
 analytics:{eyebrow:"Analytics lens",title:"Evidence for operational decisions",description:"Machine learning, statistics, scalable data workflows, and experience translating analysis into operations.",focus:["Decision support","PySpark and ML","Operations analytics"]}
};
