import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { profile } from "@/content/site";
import { siteUrl } from "@/lib/site-url";
const sans=Geist({variable:"--font-sans",subsets:["latin"]}); const mono=Geist_Mono({variable:"--font-mono",subsets:["latin"]});
export const metadata:Metadata={metadataBase:siteUrl,title:{default:"Soumyabrata Ghosh — Human-Centered AI & Software Systems",template:"%s — Soumyabrata Ghosh"},description:profile.introduction,alternates:{canonical:"/"},openGraph:{type:"profile",title:"Soumyabrata Ghosh — Human-Centered AI & Software Systems",description:profile.statement,url:"/",images:[{url:"/opengraph-image",width:1200,height:630,alt:"Soumyabrata Ghosh — Human-Centered AI, Trustworthy AI, and Human–Agent Decision Systems"}]},twitter:{card:"summary_large_image",title:"Soumyabrata Ghosh — Human-Centered AI & Software Systems",description:profile.statement,images:["/opengraph-image"]}};
export default function RootLayout({children}:{children:React.ReactNode}){const schema={"@context":"https://schema.org","@type":"ProfilePage",url:siteUrl.toString(),mainEntity:{"@type":"Person",name:profile.name,email:`mailto:${profile.email}`,homeLocation:{"@type":"Place",name:profile.location},description:profile.introduction,alumniOf:[{"@type":"CollegeOrUniversity",name:"Clark University"},{"@type":"CollegeOrUniversity",name:"University of Kalyani"},{"@type":"CollegeOrUniversity",name:"Indian Institute of Social Welfare and Business Management"}],affiliation:{"@type":"CollegeOrUniversity",name:"Colorado State University"}}};return <html lang="en" suppressHydrationWarning><body className={`${sans.variable} ${mono.variable}`}><SiteHeader/><main id="main">{children}</main><SiteFooter/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/></body></html>}
